# Generated by Django 3.1.7 on 2021-06-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(default=3.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='lng',
            field=models.FloatField(default=4.5),
            preserve_default=False,
        ),
    ]
