# Generated by Django 3.2.8 on 2021-10-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20211027_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='xid',
            field=models.CharField(default='none', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
