# Generated by Django 3.1.7 on 2021-03-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo',
            field=models.ImageField(default='no-photo-available.png', upload_to=''),
        ),
    ]
