# Generated by Django 3.1.7 on 2021-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_auto_20210313_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='location',
            field=models.CharField(default='Not specified', max_length=50),
        ),
    ]
