# Generated by Django 3.1.7 on 2021-06-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_attraction_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='location',
        ),
        migrations.AddField(
            model_name='attraction',
            name='lat',
            field=models.FloatField(default=1.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='lng',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='type',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
