# Generated by Django 3.2.4 on 2021-08-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_alter_attraction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='photo',
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
