# Generated by Django 3.1.7 on 2021-03-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0004_attraction_location'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('transport', models.CharField(choices=[('PLANE', 'Plane'), ('CAR', 'Car'), ('BUS', 'Bus'), ('BOAT', 'BOAT'), ('PLANE&BUS', 'Plane and Bus'), ('PLANE&CAR', 'Plane and Car')], default='PLANE', max_length=30)),
                ('attractions', models.ManyToManyField(related_name='attractions', to='attractions.Attraction')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='no-photo-available.png', upload_to='travels/')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.travel')),
            ],
        ),
    ]
