# Generated by Django 3.1.7 on 2021-06-06 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractions', '0005_auto_20210606_1035'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='no-photo-available.png', upload_to='travels/')),
                ('date', models.DateField()),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=100)),
                ('distance', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('polyline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
            ],
        ),
        migrations.RemoveField(
            model_name='travel',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='transport',
        ),
        migrations.AddField(
            model_name='travel',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TravelImage',
        ),
        migrations.AddField(
            model_name='travelroute',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destination', to='travels.travelstop'),
        ),
        migrations.AddField(
            model_name='travelroute',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_start', to='travels.travelstop'),
        ),
        migrations.AddField(
            model_name='travelroute',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.travel'),
        ),
        migrations.AddField(
            model_name='travelphoto',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travels.travel'),
        ),
    ]
