# Generated by Django 3.2.4 on 2021-06-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20210606_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travelphoto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travelroute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travelstop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
