# Generated by Django 3.2.4 on 2021-08-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_id'),
        ('travels', '0004_alter_travel_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel'),
        ),
    ]
