# Generated by Django 3.2.4 on 2021-08-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_alter_travel_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelroute',
            name='travel',
        ),
        migrations.AddField(
            model_name='travelstop',
            name='travel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.travel'),
            preserve_default=False,
        ),
    ]
