# Generated by Django 3.2.4 on 2021-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_auto_20210829_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelroute',
            name='polyline',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='travelroute',
            name='transport',
            field=models.CharField(choices=[('car', 'car'), ('truck', 'truck'), ('pedestrian', 'pedestrian'), ('bicycle', 'bicycle'), ('scooter', 'scooter')], max_length=100),
        ),
    ]
